apiVersion: v1
kind: Pod
metadata:
  name: stress-example
spec:
  containers:
  - image: techworldwithsiva/stress
    name: stress
    command: ["stress-ng","--cpu","1"]
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "150m"
        memory: "300Mi"