---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - max:
      cpu: "500m"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "256Mi"
    type: Pod
  - max:
      cpu: "500m"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "256Mi"
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: limit-example
spec:
  containers:
  - image: techworldwithsiva/stress
    name: limit
    command: ["stress-ng","--cpu","1"]
 
