apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-pv
  labels:
    type: ebs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0b00746678400b99b
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: my-ebs-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
spec:
  # nodeSelector:
  #      env: prod
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: my-ebs-pvc