---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  fileSystemId: fs-0850821d5de0492a1
  directoryPerms: "777"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  provisioningMode: efs-ap
  encrypted: "false"
  performanceMode: generalPurpose
  throughputMode: bursting
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
