---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  fileSystemId: fs-037834c788fb6cd5c
  directoryPerms: "777"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  provisioningMode: efs-ap
  encrypted: "false"
  performanceMode: generalPurpose
  throughputMode: bursting
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  volumeName: efs-volume
  volumeMode: Filesystem
  dataSource:
    kind: EFSVolumeSource
    fileSystemId: fs-037834c788fb6cd5c
    rootDirectory: "/"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
spec:
  nodeSelector:
       env: prod
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: efs-pvc